### ISSUE TITLE
Please update this package so it can be used with Laravel 9.

### ISSUE THREAD

**Issue by XEQTIONR** [tusharkhan/banglafaker#14]
**Is your feature request related to a problem? Please describe.**
I am unable to use this package with Laravel 9. There are conflicts with Laravel 9 dependencies. I have added error log below.

**Describe the solution you'd like**
Please update this package so that it can be used with Laravel 9 Dependencies.

**Additional context**
Debug log below - 
` Problem 1
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.26) does not satisfy that requirement.
    - Root composer.json requires inertiajs/inertia-laravel ^0.6.4 -> satisfiable by inertiajs/inertia-laravel[v0.6.4].
    - Root composer.json requires tusharkhan/banglafaker ^1.2 -> satisfiable by tusharkhan/banglafaker[1.2.1].
    - Conclusion: don't install laravel/framework v9.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.22.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.22.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.23.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.24.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.25.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.25.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.26.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.26.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.27.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.28.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.29.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.30.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.30.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.31.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.32.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.33.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.34.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.35.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.35.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.36.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.36.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.36.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.36.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.36.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.37.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.38.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.39.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.40.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.40.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.41.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.42.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.42.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.42.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.43.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.44.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.45.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.45.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.46.0 (conflict analysis result)
    - tusharkhan/banglafaker 1.2.1 requires illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.19.0, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - inertiajs/inertia-laravel v0.6.4 requires laravel/framework ^6.0|^7.0|^8.74|^9.0 -> satisfiable by laravel/framework[v9.19.0, ..., 9.x-dev].
    - Conclusion: don't install laravel/framework v9.19.0 (conflict analysis result)`

**Comment by tusharkhan** [comment]
I will.
