### ISSUE TITLE
Getting Issues During Vendor Publish

### ISSUE THREAD

**Issue by arif98741** [tusharkhan/banglafaker#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17213478/189495096-efc0cf4f-94d8-491a-ab65-ded50f845b1a.png)
![image](https://user-images.githubusercontent.com/17213478/189495136-8377b776-a0d8-44f2-89ad-a36bb970ddb1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tusharkhan** [comment]
Bro, i found it too. I am trying to fix this

**Comment by arif98741** [comment]
$this->mergeConfigFrom(__DIR__ . '/../tusharKhan/config/config.php', 'banglafaker');

**Comment by tusharkhan** [comment]
Thank you very much brother. This issue is fixed.
